eth1Endpoint = ""
eth2Endpoint = ""
storageApiToken = ""
account = "0xE6F2A8d12595fBe5D410f6CA0Be13695E61C6c35"
gasLimit = "3000000"
maxGasPrice = "60000000000"                            #wei
batchRequestBlocksNumber = 32
runForEntrustedLsdNetwork = false

[contracts]
lsdTokenAddress = ""
lsdFactoryAddress = ""